variable "cluster_name" {}
variable "location" {}
variable "resource_group_name" {}
variable "dns_prefix" {}
variable "node_count" {}
variable "vm_size" {}
variable "client_id" {}
variable "client_secret" {}
variable "kubernetes_version" {}
variable "admin_group_object_id" {}